name    'jhaals-app_inventory'
version '0.0.1'
author 'Johan Haals <johan.haals@gmail.com>'
license 'Expat License'
description 'Mac OS X Software Inventory'
project_page 'https://github.com/JHaals/jhaals-app_inventory'
